//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.CustomersOrders = new HashSet<CustomersOrders>();
        }
    
        public Nullable<int> emp_id { get; set; }
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_surName { get; set; }
        public string cust_address { get; set; }
        public string cust_phone { get; set; }
        public string cust_email { get; set; }
        public Nullable<System.DateTime> cust_dateBirth { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<CustomersOrders> CustomersOrders { get; set; }
    }
}
