//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirm.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
  
    public partial class CustomersOrders
    {
        public int customersOrders_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> cust_id { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
