//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirm.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Orders
    {
        public Orders()
        {
            this.CustomersOrders = new HashSet<CustomersOrders>();
            this.OrdersProducts = new HashSet<OrdersProducts>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> order_prodCount { get; set; }
        public string order_dateils { get; set; }
        public string order_status { get; set; }
        public System.DateTime order_date { get; set; }
    
        public virtual ICollection<CustomersOrders> CustomersOrders { get; set; }
        public virtual ICollection<OrdersProducts> OrdersProducts { get; set; }
    }
}
