//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrdersProducts = new HashSet<OrdersProducts>();
        }
    
        public int prod_id { get; set; }
        public string prod_name { get; set; }
        public string prod_dump { get; set; }
        public string prod_litter { get; set; }
        public string prod_oilness { get; set; }
        public string prod_density { get; set; }
        public string prod_bit { get; set; }
        public string prod_kernelImpurety { get; set; }
        public string prod_protein { get; set; }
        public Nullable<decimal> prod_Price { get; set; }
        public Nullable<int> prod_Qty { get; set; }
    
        public virtual ICollection<OrdersProducts> OrdersProducts { get; set; }
    }
}
