//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int task_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string task_name { get; set; }
        public string task_dateils { get; set; }
        public string task_status { get; set; }
        public System.DateTime task_date { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
